http:
  addr: ":8182"

db:
  dsn: "root:root@tcp(localhost:13316)/demo_payment"

redis:
  addr: "localhost:6389"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  server:
    port: 8012
    etcdTTL: 60

etcd:
  endpoints:
    - "localhost:12379"

opentelemetry:
  serviceName: "demo"
  serviceVersion: "v0.0.1"

logger:
  filename: "d:\\appcache\\elasticsearch\\logs\\payment.log"
  maxsize: 50
  maxBackups: 3
  maxAge: 7

zipkin:
  collectorURL: "http://localhost:9411/api/v2/spans"

prometheus:
  listenPort: ":8081"

remoteProvider:
  provider: "etcd3"
  endpoint: "http://127.0.0.1:12379"
  path: "/payment"
